// Generated by CoffeeScript 1.7.1
(function() {
  var models;

  models = require('../models/db');

  exports.index = function(req, res) {
    console.log(req.query['manager']);
    if (req.query['manager'] !== 'true') {
      return models.citylist(function(err, citylist) {
        res.header('Content-Type', 'application/json');
        return res.send(JSON.stringify(citylist));
      });
    } else {
      return models.citylist_manager(function(err, citylist) {
        res.header('Content-Type', 'application/json');
        return res.send(JSON.stringify(citylist));
      });
    }
  };

  exports.certain_city = function(req, res) {
    console.log(req.params.code);
    return models.certain_city(req.params.code, function(err, city) {
      res.header('Content-Type', 'application/json');
      return res.send(JSON.stringify(city));
    });
  };

  exports.random = function(req, res) {
    return models.random_city(function(err, random) {
      res.header('Content-Type', 'application/json');
      return res.send(JSON.stringify(random));
    });
  };

}).call(this);
