// Generated by CoffeeScript 1.7.1
(function() {
  var models;

  models = require('../models/db');

  exports.index = function(req, res) {
    return models.countrylist(function(err, countrylist) {
      res.header('Content-Type', 'application/json');
      return res.send(JSON.stringify(countrylist));
    });
  };

  exports.certain_country = function(req, res) {
    console.log(req.params.code);
    return models.certain_country(req.params.code, function(err, country) {
      res.header('Content-Type', 'application/json');
      return res.send(JSON.stringify(country));
    });
  };

  exports.random = function(req, res) {
    return models.random_country(function(err, random) {
      res.header('Content-Type', 'application/json');
      return res.send(JSON.stringify(random));
    });
  };

  exports.country_by_region = function(req, res) {
    return models.country_by_region(req.params.region, function(err, countries) {
      res.header('Content-Type', 'application/json');
      return res.send(JSON.stringify(countries));
    });
  };

  exports.country_by_sub_region = function(req, res) {
    return models.country_by_sub_region(req.params.sub_region, function(err, countries) {
      res.header('Content-Type', 'application/json');
      return res.send(JSON.stringify(countries));
    });
  };

  exports.country_by_region_and_sub_region = function(req, res) {
    return models.country_by_region_and_sub_region(req.params.region, req.params.sub_region, function(err, countries) {
      res.header('Content-Type', 'application/json');
      return res.send(JSON.stringify(countries));
    });
  };

}).call(this);
