// Generated by CoffeeScript 1.7.1
(function() {
  var citydata;

  citydata = require('../models/db');

  exports.index = function(req, res) {
    return res.render("index", {
      title: "Test web page on node.js using Express and Mongoose",
      pagetitle: "Hello there"
    });
  };

}).call(this);
