// Generated by CoffeeScript 1.7.1
(function() {
  var models;

  models = require('../models/db');

  exports.login = function(req, res) {
    return res.render("login", {
      title: "Test web page on node.js using Express and Mongoose",
      pagetitle: "Hello there"
    });
  };

  exports.analitics = function(req, res) {
    return res.render('manager', {
      user: req.user
    });
  };

  exports.cities_index = function(req, res) {
    return res.render('manager_cities', {
      user: req.user
    });
  };

  exports.update_city = function(req, res) {
    var data;
    data = req.body;
    console.log(data.city_name);
    return models.City.findOne({
      _id: req.params.id
    }, function(err, doc) {
      doc.city_name = data.city_name;
      doc.code = data.code;
      doc.coordinates = data.coordinates;
      doc.flickr = data.flickr;
      doc.wikipedia_array = data.wikipedia_array;
      doc.country_code = data.country_code;
      doc.place_id = data.place_id;
      doc.places = data.places;
      return doc.save(function(error) {
        if (!error) {
          return res.send("OK");
        }
      });
    });
  };

  exports.create_city = function(req, res) {
    var city, data;
    data = req.body;
    city = new models.City();
    city.city_name = data.city_name;
    city.code = data.code;
    city.coordinates = data.coordinates;
    city.flickr = data.flickr;
    city.wikipedia_array = data.wikipedia_array;
    city.country_code = data.country_code;
    city.place_id = data.place_id;
    city.places = data.places;
    city.save();
    return res.redirect("/manager/cities");
  };

}).call(this);
