// Generated by CoffeeScript 1.7.1
(function() {
  var citydata;

  citydata = require('../models/db');

  exports.index = function(req, res) {
    return citydata.random_city(function(err, random) {
      res.header('Content-Type', 'application/json');
      return res.send(JSON.stringify(random));
    });
  };

}).call(this);
